### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by SatireSage** [felomousa/felomousa.github.io#5]
Add a dark mode toggle and stylesheet

**Comment by SatireSage** [comment]
![Screen Shot 2024-02-26 at 13 49 00 PM](https://github.com/felomousa/felomousa.github.io/assets/49692422/58d1a20f-067f-42e5-87a7-5c4b9a8c880d)
Button colors all static in dark mode unlike respective colors in light mode.

**Comment by felomousa** [comment]
<img width="390" alt="image" src="https://github.com/felomousa/felomousa.github.io/assets/149443735/01653fb4-ca75-4ea1-ae2d-f790d520c620">

1. Added on-hover effects, for both text & icons.
2. Added smoother transitions between dark & light mode for background colours, icons & text.
